# 베이스 이미지 선택
FROM python:3.12-slim

# 작업 디렉토리 설정
WORKDIR /app

# 시스템 종속성 설치
RUN apt-get update && apt-get install -y \
    gcc \
    libmariadb-dev-compat \
    libmariadb-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 필요한 파일 복사 및 종속성 설치
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

# KST로 변경
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# 애플리케이션 소스 코드 복사
COPY . .

# 포트 설정
EXPOSE 8000

# 서버 실행 명령어
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD "uvicorn main:app --host 0.0.0.0 --port 8000 1>>! log.log 2>>! err.log"
